// Welcome-page copy. Chinese is confined to this UI translation catalog.
const en = {
  skip: 'Skip to setup',
  brandCaption: 'A companion to Travel Agent',
  helpLink: 'Need a hand?',
  connectionLink: 'Connection',
  eyebrow: 'YOUR CHROME TRAVEL COMPANION',
  titleOne: 'Connect Chrome.',
  titleTwo: 'Travel with an agent.',
  intro: 'Bring the travel websites and accounts you already use into your conversations with Travel Agent.',
  getStarted: 'Set up in three steps',
  desktopNote: 'Keep Travel Agent Desktop open while you use the extension.',
  previewTab: 'Your travel plans',
  previewAddress: 'Your favorite travel websites',
  previewTitle: 'A familiar browser.\nA little help along the way.',
  previewPrompt: 'Find a hotel near the Bund in Shanghai.',
  previewCaption: 'An example of a connected tab',
  setupTitle: "A quick setup. Then you're off.",
  setupSubtitle: 'Three steps to your first conversation',
  pinTitle: 'Pin Travel Browser',
  pinBody: "Open the puzzle menu in Chrome's toolbar, find Travel Browser, and click the pin.",
  chooseTitle: 'Choose Chrome in the app',
  chooseBody: 'Open New trip in Travel Agent. After Budget, choose Chrome extension before sending your first message.',
  budget: 'Budget',
  chromeChoice: 'Chrome extension',
  askTitle: 'Start with a travel question',
  askBody: 'Send your request in Travel Agent. The agent can open task tabs in your connected Chrome profile.',
  example: '“Help me compare hotels near the Bund.”',
  existingTitle: 'Already have a webpage open?',
  existingBody:
    'Click Travel Browser on that tab to let the agent use it. It joins the cyan Travel Browser group. Click the extension again to disconnect that tab.',
  helpEyebrow: 'GOOD TO KNOW',
  helpTitle: 'A little help\nalong the way.',
  helpIntro: 'You choose the browser and the pages the agent can use.',
  statusQuestion: 'What do the extension icons mean?',
  readyTitle: 'Connected',
  readyBody: 'A colored penguin marks a connected tab. Connected tabs appear in the cyan Travel Browser group.',
  idleTitle: 'Not connected',
  idleBody: 'A black penguin means this tab is not connected. Click it to authorize the tab.',
  waitingTitle: 'Connecting',
  waitingBody: 'A gray icon with a dots badge is waiting to connect. Check that Travel Agent Desktop is running.',
  errorTitle: 'Needs attention',
  errorBody:
    'A red exclamation mark signals a connection error. Hover over the icon for details. Gray without a badge can mean Chrome does not allow access to that page.',
  existingChatQuestion: 'Can I use Chrome in an existing chat?',
  existingChatAnswer:
    "Yes. When no task is running, open the Browser panel's menu in Travel Agent and choose My own Chrome (extension). Each new chat starts with the in-app browser, so choose Chrome for the chats where you want it.",
  privacyQuestion: 'What happens to my browser data?',
  privacyAnswer:
    'Your Chrome profile stays on your device. The extension connects to Travel Agent locally. To carry out your request, page content may be sent to the model provider you configured, and websites receive normal browsing traffic.',
  connectionQuestion: "Chrome isn't connecting. What can I check?",
  connectionAnswer:
    'Keep Travel Agent Desktop running and Travel Browser enabled in Chrome. Select Chrome extension in your chat. If you updated the extension files, reload Travel Browser in chrome://extensions. Open Connection on this page to check the paired application. If multiple apps are running, choose the intended one.',
  developerQuestion: 'Developer tools: CLI & MCP',
  developerIntro:
    'Optional for developers. No terminal commands are needed to use the extension with Travel Agent Desktop.',
  developerCli: 'For standalone CLI use, first choose Standalone CLI in Connection settings. From a built checkout:',
  developerMcp:
    'To start the local stdio MCP server, run penguin-browser. Editor setup is documented in MCP.md in the checkout.',
  footer: 'Made for the journey. Open source, Apache-2.0.',
  pageTitle: 'Welcome to Travel Browser',
  navigation: 'Page navigation',
  language: 'Language',
} as const

type WelcomeStrings = Record<keyof typeof en, string>
const zh: WelcomeStrings = {
  skip: '跳至设置步骤',
  brandCaption: 'Travel Agent 的 Chrome 助手',
  connectionLink: '连接设置',
  helpLink: '使用帮助',
  eyebrow: '把旅行灵感，带进你的浏览器',
  titleOne: '连接 Chrome，',
  titleTwo: '和旅行助手一起出发。',
  intro: '使用你熟悉的旅行网站和已登录的账号，在 Travel Agent 中用对话安排下一段旅程。',
  getStarted: '三步开始使用',
  desktopNote: '使用扩展时，请保持 Travel Agent 桌面应用运行。',
  previewTab: '我的旅行计划',
  previewAddress: '你常用的旅行网站',
  previewTitle: '熟悉的浏览器，\n多一位旅行帮手。',
  previewPrompt: '帮我找一家上海外滩附近的酒店。',
  previewCaption: '已连接标签页的示意',
  setupTitle: '简单设置，就能出发',
  setupSubtitle: '三步开启第一次旅行对话',
  pinTitle: '固定 Travel Browser',
  pinBody: '点击 Chrome 工具栏的拼图图标，找到 Travel Browser，再点击图钉将它固定。',
  chooseTitle: '在应用中选择 Chrome',
  chooseBody: '在 Travel Agent 中打开「新行程」，通过「预算」后面的按钮选择「Chrome 扩展」，再发送第一条消息。',
  budget: '预算',
  chromeChoice: 'Chrome 扩展',
  askTitle: '说说你的旅行需求',
  askBody: '回到 Travel Agent 发送需求。助手就可以在已连接的 Chrome 中打开任务所需的网页。',
  example: '“帮我比较一下外滩附近的酒店。”',
  existingTitle: '想使用已经打开的网页？',
  existingBody:
    '在那个标签页点击 Travel Browser 图标，即可授权助手使用该页。它会加入青色的 Travel Browser 分组。再次点击扩展图标，可以断开该标签页。',
  helpEyebrow: '出发前的小贴士',
  helpTitle: '使用过程中的\n几个小问题',
  helpIntro: '使用哪个浏览器、哪些网页，都由你决定。',
  statusQuestion: '扩展图标代表什么状态？',
  readyTitle: '已连接',
  readyBody: '彩色企鹅表示该标签页已连接。连接的标签页会加入青色的 Travel Browser 分组。',
  idleTitle: '未连接',
  idleBody: '黑色企鹅表示该标签页尚未连接。点击图标即可授权使用该页。',
  waitingTitle: '正在连接',
  waitingBody: '带有省略号徽标的灰色图标表示正在等待连接。请检查 Travel Agent 桌面应用是否正在运行。',
  errorTitle: '需要处理',
  errorBody:
    '红色感叹号表示连接出现问题，悬停在图标上可查看原因。没有徽标的灰色图标也可能表示 Chrome 不允许访问当前页面。',
  existingChatQuestion: '已有对话也可以使用 Chrome 吗？',
  existingChatAnswer:
    '可以。在任务未运行时，打开 Travel Agent 的浏览器面板菜单，选择「我自己的 Chrome（扩展）」。每次新对话仍默认使用应用内浏览器，需要使用 Chrome 时请主动选择。',
  privacyQuestion: '浏览器数据会如何使用？',
  privacyAnswer:
    'Chrome 的个人资料保存在你的设备上，扩展通过本地连接与 Travel Agent 通信。为完成你的请求，网页内容可能会发送给你配置的模型服务商；访问网站时也会产生正常的网络请求。',
  connectionQuestion: 'Chrome 没连上，可以检查什么？',
  connectionAnswer:
    '请保持 Travel Agent 桌面应用运行，并确认 Chrome 中已启用 Travel Browser。在对话中选择「Chrome 扩展」。若刚更新过扩展文件，请在 chrome://extensions 中重新加载 Travel Browser；在本页的「连接设置」中检查配对的应用；同时运行多个应用时，请选择你要连接的那个。',
  developerQuestion: '开发者工具：CLI 与 MCP',
  developerIntro: '供开发者选用。配合 Travel Agent 桌面应用使用时，无需执行终端命令。',
  developerCli: '独立使用 CLI 时，先在「连接设置」中选择「独立 CLI」，再从已构建的项目运行：',
  developerMcp: '启动本地 stdio MCP 服务可运行 penguin-browser。编辑器配置方法见项目中的 MCP.md。',
  footer: '陪你安排下一程 · Apache-2.0 开源许可',
  pageTitle: '欢迎使用 Travel Browser',
  navigation: '页面导航',
  language: '语言',
}

export const welcomeStrings = { en, zh }
export type WelcomeLanguage = keyof typeof welcomeStrings
