export * from './relay/cdp-relay.js'
export * from './shared/utils.js'
export { getCDPSessionForPage, PlaywrightCDPSessionAdapter } from './relay/cdp-session.js'
export type { ICDPSession } from './relay/cdp-session.js'
export { Editor } from './page/editor.js'
export type { ReadResult, SearchMatch, EditResult } from './page/editor.js'
export { Debugger } from './page/debugger.js'
export type { BreakpointInfo, LocationInfo, EvaluateResult, ScriptInfo } from './page/debugger.js'
export { getAriaSnapshot, showAriaRefLabels, hideAriaRefLabels } from './page/aria-snapshot.js'
export type { AriaRef, AriaSnapshotResult } from './page/aria-snapshot.js'
export { startRecording, stopRecording, isRecording, cancelRecording } from './media/screen-recording.js'
export type { StartRecordingOptions, StopRecordingOptions, RecordingState } from './media/screen-recording.js'
