/**
 * Curated generated cover library for travel-oriented, non-evidentiary surfaces.
 *
 * These images are decorative. A real browser screenshot or a sourced POI image must take
 * priority when one exists; this catalog is the honest fallback for welcome-screen cards.
 * Every entry points at an optimized project asset and keeps enough generation metadata to
 * be regenerated or replaced without changing the selection API.
 */

export type TravelCoverKind = "destination" | "activity" | "season" | "generic";
export type TravelCoverTone = "dark" | "cool" | "warm" | "light";

export interface TravelCoverAsset {
  id: string;
  src: string;
  kind: TravelCoverKind;
  subject: string;
  tags: readonly string[];
  keywords: readonly string[];
  seasons: readonly ("spring" | "summer" | "autumn" | "winter" | "all")[];
  tone: TravelCoverTone;
  /** CSS object-position tuned for the card crop. */
  focalPoint: string;
  source: "generated";
  promptVersion: 1 | 2;
}

const cover = (
  id: string,
  kind: TravelCoverKind,
  subject: string,
  tags: readonly string[],
  keywords: readonly string[],
  seasons: TravelCoverAsset["seasons"],
  tone: TravelCoverTone,
  focalPoint = "50% 50%",
  promptVersion: TravelCoverAsset["promptVersion"] = 1,
): TravelCoverAsset => ({
  id,
  src: `/travel-covers/${id}.jpg`,
  kind,
  subject,
  tags,
  keywords,
  seasons,
  tone,
  focalPoint,
  source: "generated",
  promptVersion,
});

export const TRAVEL_COVER_CATALOG: readonly TravelCoverAsset[] = [
  // 96 destination scenes.
  cover(
    "tokyo-night",
    "destination",
    "Tokyo at blue hour",
    ["asia", "japan", "city", "night", "culture"],
    ["tokyo", "东京", "東京"],
    ["all"],
    "dark",
    "50% 43%",
  ),
  cover(
    "kyoto-temple",
    "destination",
    "Kyoto temple lane",
    ["asia", "japan", "temple", "culture", "autumn"],
    ["kyoto", "京都"],
    ["autumn", "all"],
    "warm",
    "50% 45%",
  ),
  cover(
    "seoul-rooftops",
    "destination",
    "Seoul rooftops at dusk",
    ["asia", "korea", "city", "culture", "night"],
    ["seoul", "korea", "首尔", "首爾", "韩国", "韓國"],
    ["all"],
    "cool",
    "50% 42%",
  ),
  cover(
    "bangkok-river",
    "destination",
    "Bangkok river at golden hour",
    ["asia", "thailand", "river", "city", "temple"],
    ["bangkok", "thailand", "曼谷", "泰国", "泰國"],
    ["all"],
    "warm",
    "50% 44%",
  ),
  cover(
    "singapore-gardens",
    "destination",
    "Singapore tropical city gardens",
    ["asia", "singapore", "city", "garden", "tropical"],
    ["singapore", "新加坡", "狮城", "獅城"],
    ["all"],
    "cool",
    "50% 45%",
  ),
  cover(
    "bali-rice",
    "destination",
    "Bali rice terraces",
    ["asia", "indonesia", "island", "nature", "tropical"],
    ["bali", "indonesia", "巴厘", "巴釐", "印度尼西亚", "印尼"],
    ["all"],
    "light",
    "50% 44%",
  ),
  cover(
    "paris-rooftops",
    "destination",
    "Paris rooftops at blue hour",
    ["europe", "france", "city", "romantic", "culture"],
    ["paris", "france", "巴黎", "法国", "法國"],
    ["all"],
    "cool",
    "50% 40%",
  ),
  cover(
    "rome-street",
    "destination",
    "Roman cobblestone street",
    ["europe", "italy", "city", "history", "food"],
    ["rome", "italy", "罗马", "羅馬", "意大利", "義大利"],
    ["all"],
    "warm",
    "50% 45%",
  ),
  cover(
    "barcelona-coast",
    "destination",
    "Barcelona waterfront",
    ["europe", "spain", "city", "coast", "food"],
    ["barcelona", "spain", "巴塞罗那", "巴塞羅那", "西班牙"],
    ["spring", "summer", "autumn"],
    "light",
    "50% 43%",
  ),
  cover(
    "amsterdam-canals",
    "destination",
    "Amsterdam canal houses",
    ["europe", "netherlands", "city", "canal", "culture"],
    ["amsterdam", "netherlands", "阿姆斯特丹", "荷兰", "荷蘭"],
    ["all"],
    "cool",
    "50% 43%",
  ),
  cover(
    "swiss-alps",
    "destination",
    "Swiss alpine lake and cabin",
    ["europe", "switzerland", "mountain", "lake", "nature"],
    ["swiss", "switzerland", "alps", "瑞士", "阿尔卑斯", "阿爾卑斯"],
    ["all"],
    "cool",
    "55% 43%",
  ),
  cover(
    "greek-island",
    "destination",
    "Greek island coast",
    ["europe", "greece", "island", "coast", "summer"],
    ["greece", "greek", "santorini", "希腊", "希臘", "圣托里尼", "聖托里尼"],
    ["spring", "summer", "autumn"],
    "light",
    "50% 42%",
  ),
  cover(
    "new-york-rooftop",
    "destination",
    "New York rooftop skyline",
    ["americas", "usa", "city", "skyline", "night"],
    ["new york", "nyc", "manhattan", "纽约", "紐約", "曼哈顿", "曼哈頓"],
    ["all"],
    "dark",
    "50% 42%",
  ),
  cover(
    "san-francisco-bay",
    "destination",
    "San Francisco Bay",
    ["americas", "usa", "city", "coast", "road"],
    ["san francisco", "sf", "旧金山", "舊金山", "三藩市"],
    ["all"],
    "cool",
    "50% 43%",
  ),
  cover(
    "quebec-winter",
    "destination",
    "Old Quebec in winter",
    ["americas", "canada", "city", "snow", "history"],
    ["quebec", "canada", "魁北克", "加拿大"],
    ["winter"],
    "cool",
    "50% 45%",
  ),
  cover(
    "patagonia-lake",
    "destination",
    "Patagonia mountain lake",
    ["americas", "argentina", "chile", "mountain", "hiking"],
    ["patagonia", "argentina", "chile", "巴塔哥尼亚", "巴塔哥尼亞", "阿根廷", "智利"],
    ["spring", "summer", "autumn"],
    "cool",
    "50% 42%",
  ),
  cover(
    "marrakech-courtyard",
    "destination",
    "Marrakech riad courtyard",
    ["africa", "morocco", "city", "culture", "architecture"],
    ["marrakech", "morocco", "马拉喀什", "馬拉喀什", "摩洛哥"],
    ["all"],
    "warm",
    "50% 48%",
  ),
  cover(
    "cape-town-coast",
    "destination",
    "Cape Town coast",
    ["africa", "south-africa", "coast", "mountain", "road"],
    ["cape town", "south africa", "开普敦", "開普敦", "南非"],
    ["all"],
    "cool",
    "50% 42%",
  ),
  cover(
    "dubai-desert",
    "destination",
    "Dubai desert retreat",
    ["middle-east", "uae", "desert", "city", "luxury"],
    ["dubai", "uae", "迪拜", "杜拜", "阿联酋", "阿聯酋"],
    ["autumn", "winter", "spring"],
    "warm",
    "50% 44%",
  ),
  cover(
    "sydney-harbour",
    "destination",
    "Sydney harbour morning",
    ["oceania", "australia", "city", "harbour", "coast"],
    ["sydney", "australia", "悉尼", "雪梨", "澳大利亚", "澳洲"],
    ["all"],
    "light",
    "50% 41%",
  ),
  cover(
    "new-zealand-fjord",
    "destination",
    "New Zealand fjord",
    ["oceania", "new-zealand", "fjord", "mountain", "nature"],
    ["new zealand", "milford", "queenstown", "新西兰", "紐西蘭", "皇后镇", "皇后鎮"],
    ["all"],
    "cool",
    "50% 42%",
  ),
  cover(
    "shanghai-night",
    "destination",
    "Shanghai waterfront at night",
    ["asia", "china", "city", "skyline", "night"],
    ["shanghai", "上海", "外滩", "外灘"],
    ["all"],
    "dark",
    "50% 40%",
  ),
  cover(
    "hangzhou-west-lake",
    "destination",
    "Hangzhou West Lake",
    ["asia", "china", "lake", "garden", "culture"],
    ["hangzhou", "west lake", "杭州", "西湖"],
    ["all"],
    "cool",
    "50% 43%",
  ),
  cover(
    "yunnan-old-town",
    "destination",
    "Yunnan old town",
    ["asia", "china", "mountain", "culture", "old-town"],
    ["yunnan", "lijiang", "dali", "云南", "雲南", "丽江", "麗江", "大理"],
    ["all"],
    "warm",
    "50% 44%",
  ),
  cover(
    "beijing-hutong-dawn",
    "destination",
    "Beijing hutong at dawn",
    ["asia", "china", "city", "culture", "spring"],
    ["beijing", "hutong", "北京", "胡同"],
    ["spring", "all"],
    "warm",
    "50% 44%",
    2,
  ),
  cover(
    "hong-kong-harbour-rain",
    "destination",
    "Hong Kong harbour after rain",
    ["asia", "china", "city", "harbour", "rain"],
    ["hong kong", "香港"],
    ["summer", "all"],
    "cool",
    "54% 40%",
    2,
  ),
  cover(
    "taipei-teahouse-lane",
    "destination",
    "Taipei hillside lane in rain",
    ["asia", "taiwan", "city", "tea", "rain"],
    ["taipei", "taiwan", "台北", "台湾", "臺灣"],
    ["autumn", "all"],
    "cool",
    "48% 43%",
    2,
  ),
  cover(
    "osaka-canal-evening",
    "destination",
    "Osaka canal in the evening",
    ["asia", "japan", "city", "canal", "night"],
    ["osaka", "大阪"],
    ["all"],
    "dark",
    "50% 41%",
    2,
  ),
  cover(
    "hokkaido-flower-fields",
    "destination",
    "Hokkaido flower fields",
    ["asia", "japan", "flowers", "countryside", "summer"],
    ["hokkaido", "北海道"],
    ["summer"],
    "light",
    "52% 42%",
    2,
  ),
  cover(
    "jeju-volcanic-coast",
    "destination",
    "Jeju volcanic coast",
    ["asia", "korea", "island", "coast", "nature"],
    ["jeju", "jeju island", "济州", "濟州", "济州岛", "濟州島"],
    ["spring", "summer", "autumn"],
    "cool",
    "52% 41%",
    2,
  ),
  cover(
    "guilin-karst-river",
    "destination",
    "Guilin karst river in mist",
    ["asia", "china", "river", "mountain", "nature"],
    ["guilin", "yangshuo", "桂林", "阳朔", "陽朔"],
    ["spring", "all"],
    "cool",
    "50% 39%",
    2,
  ),
  cover(
    "chengdu-teahouse-garden",
    "destination",
    "Chengdu garden teahouse",
    ["asia", "china", "city", "tea", "garden"],
    ["chengdu", "成都"],
    ["summer", "all"],
    "cool",
    "50% 46%",
    2,
  ),
  cover(
    "hanoi-old-quarter",
    "destination",
    "Hanoi old-quarter street",
    ["asia", "vietnam", "city", "culture", "old-town"],
    ["hanoi", "vietnam", "河内", "河內", "越南"],
    ["spring", "all"],
    "warm",
    "48% 43%",
    2,
  ),
  cover(
    "hoi-an-lantern-dusk",
    "destination",
    "Hoi An riverside at dusk",
    ["asia", "vietnam", "river", "old-town", "night"],
    ["hoi an", "hoian", "会安", "會安"],
    ["all"],
    "dark",
    "50% 42%",
    2,
  ),
  cover(
    "chiang-mai-mountain-temple",
    "destination",
    "Chiang Mai mountain temple mood",
    ["asia", "thailand", "mountain", "temple", "culture"],
    ["chiang mai", "thailand", "清迈", "清邁", "泰国", "泰國"],
    ["all"],
    "warm",
    "50% 43%",
    2,
  ),
  cover(
    "luang-prabang-mekong",
    "destination",
    "Luang Prabang Mekong morning",
    ["asia", "laos", "river", "mountain", "slow-travel"],
    ["luang prabang", "laos", "琅勃拉邦", "老挝", "寮國"],
    ["all"],
    "warm",
    "52% 40%",
    2,
  ),
  cover(
    "palawan-lagoon",
    "destination",
    "Palawan limestone lagoon",
    ["asia", "philippines", "island", "lagoon", "nature"],
    ["palawan", "philippines", "巴拉望", "菲律宾", "菲律賓"],
    ["summer", "all"],
    "light",
    "53% 41%",
    2,
  ),
  cover(
    "borneo-rainforest-river",
    "destination",
    "Borneo rainforest river",
    ["asia", "borneo", "rainforest", "river", "nature"],
    ["borneo", "婆罗洲", "婆羅洲", "加里曼丹"],
    ["all"],
    "cool",
    "50% 41%",
    2,
  ),
  cover(
    "kerala-backwaters",
    "destination",
    "Kerala backwaters morning",
    ["asia", "india", "river", "tropical", "slow-travel"],
    ["kerala", "india", "喀拉拉", "印度"],
    ["all"],
    "warm",
    "52% 43%",
    2,
  ),
  cover(
    "melbourne-laneway-morning",
    "destination",
    "Melbourne laneway morning",
    ["oceania", "australia", "city", "cafe", "culture"],
    ["melbourne", "australia", "墨尔本", "墨爾本", "澳大利亚", "澳洲"],
    ["autumn", "all"],
    "warm",
    "48% 44%",
    2,
  ),
  cover(
    "tasmania-wild-coast",
    "destination",
    "Tasmania wild coast",
    ["oceania", "australia", "coast", "nature", "road"],
    ["tasmania", "塔斯马尼亚", "塔斯馬尼亞"],
    ["spring", "all"],
    "cool",
    "52% 40%",
    2,
  ),
  cover(
    "fiji-lagoon",
    "destination",
    "Fiji island lagoon",
    ["oceania", "fiji", "island", "lagoon", "tropical"],
    ["fiji", "斐济", "斐濟"],
    ["summer", "all"],
    "light",
    "50% 42%",
    2,
  ),

  cover(
    "london-riverside-morning",
    "destination",
    "London riverside in the morning",
    ["europe", "uk", "england", "city", "river", "spring"],
    ["london", "england", "uk", "伦敦", "倫敦", "英国", "英國"],
    ["spring", "all"],
    "cool",
    "50% 42%",
    2,
  ),
  cover(
    "edinburgh-old-town-mist",
    "destination",
    "Edinburgh old town in mist",
    ["europe", "uk", "scotland", "city", "history", "autumn"],
    ["edinburgh", "scotland", "爱丁堡", "愛丁堡", "苏格兰", "蘇格蘭"],
    ["autumn", "all"],
    "cool",
    "50% 42%",
    2,
  ),
  cover(
    "lisbon-hillside-tram",
    "destination",
    "Lisbon hillside tram",
    ["europe", "portugal", "city", "tram", "summer"],
    ["lisbon", "portugal", "里斯本", "葡萄牙"],
    ["summer", "all"],
    "warm",
    "48% 45%",
    2,
  ),
  cover(
    "porto-riverside-dawn",
    "destination",
    "Porto riverside at dawn",
    ["europe", "portugal", "city", "river", "dawn"],
    ["porto", "oporto", "波尔图", "波爾圖"],
    ["spring", "summer", "autumn", "all"],
    "warm",
    "52% 41%",
    2,
  ),
  cover(
    "venice-canal-morning",
    "destination",
    "Venice canal in the morning",
    ["europe", "italy", "city", "canal", "spring"],
    ["venice", "italy", "威尼斯", "意大利", "義大利"],
    ["spring", "all"],
    "warm",
    "50% 44%",
    2,
  ),
  cover(
    "florence-rooftops-sunset",
    "destination",
    "Florence rooftops at sunset",
    ["europe", "italy", "city", "rooftops", "autumn"],
    ["florence", "tuscany", "佛罗伦萨", "佛羅倫斯", "托斯卡纳", "托斯卡納"],
    ["autumn", "all"],
    "warm",
    "50% 40%",
    2,
  ),
  cover(
    "vienna-cafe-street",
    "destination",
    "Vienna cafe street",
    ["europe", "austria", "city", "cafe", "winter"],
    ["vienna", "austria", "维也纳", "維也納", "奥地利", "奧地利"],
    ["winter", "all"],
    "cool",
    "50% 45%",
    2,
  ),
  cover(
    "prague-rooftops-dawn",
    "destination",
    "Prague rooftops at dawn",
    ["europe", "czechia", "city", "rooftops", "spring"],
    ["prague", "czechia", "czech republic", "布拉格", "捷克"],
    ["spring", "all"],
    "warm",
    "52% 40%",
    2,
  ),
  cover(
    "budapest-danube-evening",
    "destination",
    "Budapest and the Danube in the evening",
    ["europe", "hungary", "city", "river", "night"],
    ["budapest", "hungary", "danube", "布达佩斯", "布達佩斯", "匈牙利", "多瑙河"],
    ["all"],
    "dark",
    "50% 41%",
    2,
  ),
  cover(
    "copenhagen-harbour",
    "destination",
    "Copenhagen harbour",
    ["europe", "denmark", "city", "harbour", "cycling", "summer"],
    ["copenhagen", "denmark", "哥本哈根", "丹麦", "丹麥"],
    ["summer", "all"],
    "light",
    "48% 44%",
    2,
  ),
  cover(
    "stockholm-archipelago",
    "destination",
    "Stockholm archipelago",
    ["europe", "sweden", "island", "nature", "summer"],
    ["stockholm", "sweden", "archipelago", "斯德哥尔摩", "斯德哥爾摩", "瑞典", "群岛", "群島"],
    ["summer", "all"],
    "cool",
    "52% 42%",
    2,
  ),
  cover(
    "norwegian-fjord-village",
    "destination",
    "Norwegian fjord village",
    ["europe", "norway", "fjord", "village", "spring"],
    ["norway", "norwegian fjord", "挪威", "峡湾", "峽灣"],
    ["spring", "summer", "all"],
    "cool",
    "50% 39%",
    2,
  ),
  cover(
    "iceland-black-sand-coast",
    "destination",
    "Icelandic black-sand coast",
    ["europe", "iceland", "coast", "nature", "winter"],
    ["iceland", "black sand", "冰岛", "冰島", "黑沙滩", "黑沙灘"],
    ["winter", "all"],
    "cool",
    "52% 40%",
    2,
  ),
  cover(
    "bavarian-alpine-village",
    "destination",
    "Bavarian alpine village",
    ["europe", "germany", "bavaria", "village", "mountain", "autumn"],
    ["bavaria", "germany", "巴伐利亚", "巴伐利亞", "德国", "德國"],
    ["autumn", "all"],
    "light",
    "50% 43%",
    2,
  ),
  cover(
    "provence-lavender-road",
    "destination",
    "Provence lavender road",
    ["europe", "france", "provence", "countryside", "summer"],
    ["provence", "lavender", "普罗旺斯", "普羅旺斯", "薰衣草"],
    ["summer"],
    "warm",
    "50% 44%",
    2,
  ),
  cover(
    "croatian-adriatic-town",
    "destination",
    "Croatian Adriatic town",
    ["europe", "croatia", "coast", "town", "summer"],
    ["croatia", "adriatic", "克罗地亚", "克羅地亞", "亚得里亚海", "亞得里亞海"],
    ["summer", "all"],
    "light",
    "52% 42%",
    2,
  ),
  cover(
    "slovenia-lake-morning",
    "destination",
    "Slovenian lake in the morning",
    ["europe", "slovenia", "lake", "mountain", "autumn"],
    ["slovenia", "斯洛文尼亚", "斯洛文尼亞"],
    ["autumn", "all"],
    "warm",
    "50% 41%",
    2,
  ),
  cover(
    "ireland-atlantic-cliffs",
    "destination",
    "Irish Atlantic cliffs",
    ["europe", "ireland", "coast", "cliffs", "spring"],
    ["ireland", "irish coast", "爱尔兰", "愛爾蘭", "大西洋悬崖", "大西洋懸崖"],
    ["spring", "all"],
    "cool",
    "50% 40%",
    2,
  ),

  cover(
    "los-angeles-coast-sunset",
    "destination",
    "Los Angeles coast at sunset",
    ["north-america", "usa", "california", "city", "coast", "summer"],
    ["los angeles", "california", "洛杉矶", "洛杉磯", "加州"],
    ["summer", "all"],
    "warm",
    "52% 40%",
    2,
  ),
  cover(
    "yosemite-valley-morning",
    "destination",
    "Yosemite valley in the morning",
    ["north-america", "usa", "california", "nature", "mountain", "spring"],
    ["yosemite", "优胜美地", "優勝美地", "约塞米蒂", "約塞米蒂"],
    ["spring", "all"],
    "cool",
    "50% 39%",
    2,
  ),
  cover(
    "utah-canyon-road",
    "destination",
    "Utah canyon road",
    ["north-america", "usa", "utah", "desert", "road", "autumn"],
    ["utah", "canyon country", "犹他", "猶他", "峡谷公路", "峽谷公路"],
    ["autumn", "all"],
    "warm",
    "50% 44%",
    2,
  ),
  cover(
    "hawaii-volcanic-coast",
    "destination",
    "Hawaii volcanic coast",
    ["north-america", "usa", "hawaii", "island", "coast", "summer"],
    ["hawaii", "夏威夷", "火山海岸"],
    ["summer", "all"],
    "cool",
    "52% 41%",
    2,
  ),
  cover(
    "chicago-river-dawn",
    "destination",
    "Chicago river at dawn",
    ["north-america", "usa", "chicago", "city", "river", "spring"],
    ["chicago", "芝加哥"],
    ["spring", "all"],
    "cool",
    "50% 40%",
    2,
  ),
  cover(
    "new-orleans-courtyard",
    "destination",
    "New Orleans courtyard",
    ["north-america", "usa", "new-orleans", "city", "garden"],
    ["new orleans", "louisiana", "新奥尔良", "紐奧良", "路易斯安那"],
    ["spring", "all"],
    "cool",
    "50% 45%",
    2,
  ),
  cover(
    "miami-art-deco-morning",
    "destination",
    "Miami art-deco morning",
    ["north-america", "usa", "miami", "city", "architecture", "winter"],
    ["miami", "florida", "迈阿密", "邁阿密", "佛罗里达", "佛羅里達"],
    ["winter", "all"],
    "light",
    "50% 43%",
    2,
  ),
  cover(
    "vancouver-harbour-mountains",
    "destination",
    "Vancouver harbour and mountains",
    ["north-america", "canada", "vancouver", "city", "harbour", "mountain"],
    ["vancouver", "温哥华", "溫哥華"],
    ["spring", "all"],
    "cool",
    "52% 40%",
    2,
  ),
  cover(
    "banff-turquoise-lake",
    "destination",
    "Banff turquoise lake",
    ["north-america", "canada", "banff", "lake", "mountain", "summer"],
    ["banff", "canadian rockies", "班夫", "加拿大落基山"],
    ["summer", "all"],
    "cool",
    "50% 40%",
    2,
  ),
  cover(
    "toronto-islands-skyline",
    "destination",
    "Toronto islands and skyline",
    ["north-america", "canada", "toronto", "city", "island", "summer"],
    ["toronto", "多伦多", "多倫多"],
    ["summer", "all"],
    "light",
    "50% 41%",
    2,
  ),
  cover(
    "alaska-glacier-bay",
    "destination",
    "Alaska glacier bay",
    ["north-america", "usa", "alaska", "glacier", "nature", "summer"],
    ["alaska", "glacier bay", "阿拉斯加", "冰川湾", "冰川灣"],
    ["summer", "all"],
    "cool",
    "52% 39%",
    2,
  ),
  cover(
    "mexico-city-courtyard",
    "destination",
    "Mexico City courtyard",
    ["latin-america", "mexico", "mexico-city", "city", "garden", "spring"],
    ["mexico city", "mexico", "墨西哥城", "墨西哥"],
    ["spring", "all"],
    "warm",
    "50% 45%",
    2,
  ),
  cover(
    "costa-rica-cloud-forest",
    "destination",
    "Costa Rica cloud forest",
    ["latin-america", "costa-rica", "rainforest", "nature", "rain"],
    ["costa rica", "cloud forest", "哥斯达黎加", "哥斯達黎加", "云雾森林", "雲霧森林"],
    ["summer", "all"],
    "cool",
    "50% 42%",
    2,
  ),
  cover(
    "havana-seafront-dawn",
    "destination",
    "Havana seafront at dawn",
    ["latin-america", "cuba", "havana", "city", "coast", "dawn"],
    ["havana", "cuba", "哈瓦那", "古巴"],
    ["all"],
    "warm",
    "50% 43%",
    2,
  ),
  cover(
    "cartagena-balconies",
    "destination",
    "Cartagena balconies",
    ["latin-america", "colombia", "cartagena", "city", "architecture"],
    ["cartagena", "colombia", "卡塔赫纳", "卡塔赫納", "哥伦比亚", "哥倫比亞"],
    ["all"],
    "warm",
    "50% 44%",
    2,
  ),
  cover(
    "rio-coast-morning",
    "destination",
    "Rio coast in the morning",
    ["latin-america", "brazil", "rio", "city", "coast", "summer"],
    ["rio", "rio de janeiro", "brazil", "里约", "里約", "里约热内卢", "里約熱內盧", "巴西"],
    ["summer", "all"],
    "light",
    "52% 40%",
    2,
  ),
  cover(
    "cusco-andean-rooftops",
    "destination",
    "Cusco Andean rooftops",
    ["latin-america", "peru", "cusco", "city", "mountain", "dawn"],
    ["cusco", "peru", "库斯科", "庫斯科", "秘鲁", "秘魯"],
    ["autumn", "winter", "all"],
    "warm",
    "50% 41%",
    2,
  ),
  cover(
    "buenos-aires-cafe-street",
    "destination",
    "Buenos Aires cafe street",
    ["latin-america", "argentina", "buenos-aires", "city", "cafe", "autumn"],
    ["buenos aires", "argentina", "布宜诺斯艾利斯", "布宜諾斯艾利斯", "阿根廷"],
    ["autumn", "all"],
    "warm",
    "50% 45%",
    2,
  ),

  cover(
    "kanazawa-garden-winter",
    "destination",
    "Kanazawa garden in winter",
    ["east-asia", "japan", "kanazawa", "garden", "winter"],
    ["kanazawa", "金泽", "金澤"],
    ["winter", "all"],
    "cool",
    "50% 43%",
    2,
  ),
  cover(
    "busan-coast-morning",
    "destination",
    "Busan coast in the morning",
    ["east-asia", "korea", "busan", "city", "coast", "spring"],
    ["busan", "釜山"],
    ["spring", "all"],
    "light",
    "52% 41%",
    2,
  ),
  cover(
    "zhangjiajie-mist-mountains",
    "destination",
    "Zhangjiajie mountains in mist",
    ["east-asia", "china", "zhangjiajie", "nature", "mountain", "mist"],
    ["zhangjiajie", "张家界", "張家界"],
    ["spring", "all"],
    "cool",
    "50% 38%",
    2,
  ),
  cover(
    "mongolia-steppe-camp",
    "destination",
    "Mongolian steppe camp",
    ["east-asia", "mongolia", "steppe", "camp", "summer"],
    ["mongolia", "steppe", "蒙古", "草原"],
    ["summer", "all"],
    "warm",
    "52% 43%",
    2,
  ),
  cover(
    "kuala-lumpur-tropical-rooftops",
    "destination",
    "Kuala Lumpur tropical rooftops",
    ["southeast-asia", "malaysia", "kuala-lumpur", "city", "tropical", "rain"],
    ["kuala lumpur", "malaysia", "吉隆坡", "马来西亚", "馬來西亞"],
    ["all"],
    "cool",
    "50% 40%",
    2,
  ),
  cover(
    "siem-reap-forest-temples",
    "destination",
    "Siem Reap forest temples",
    ["southeast-asia", "cambodia", "siem-reap", "forest", "temple"],
    ["siem reap", "cambodia", "暹粒", "柬埔寨"],
    ["all"],
    "cool",
    "50% 42%",
    2,
  ),
  cover(
    "komodo-island-coast",
    "destination",
    "Komodo island coast",
    ["southeast-asia", "indonesia", "komodo", "island", "coast", "summer"],
    ["komodo", "科莫多"],
    ["summer", "all"],
    "light",
    "52% 40%",
    2,
  ),
  cover(
    "jaipur-courtyard-morning",
    "destination",
    "Jaipur courtyard in the morning",
    ["south-asia", "india", "jaipur", "courtyard", "architecture"],
    ["jaipur", "india", "斋浦尔", "齋浦爾", "印度"],
    ["all"],
    "warm",
    "50% 44%",
    2,
  ),
  cover(
    "nepal-himalayan-village",
    "destination",
    "Nepalese Himalayan village",
    ["south-asia", "nepal", "himalaya", "village", "autumn"],
    ["nepal", "himalaya", "尼泊尔", "尼泊爾", "喜马拉雅", "喜馬拉雅"],
    ["autumn", "all"],
    "cool",
    "50% 42%",
    2,
  ),
  cover(
    "sri-lanka-tea-hills",
    "destination",
    "Sri Lankan tea hills",
    ["south-asia", "sri-lanka", "tea", "hills", "mist"],
    ["sri lanka", "斯里兰卡", "斯里蘭卡"],
    ["all"],
    "cool",
    "52% 41%",
    2,
  ),
  cover(
    "istanbul-bosphorus-dawn",
    "destination",
    "Istanbul and the Bosphorus at dawn",
    ["middle-east", "turkey", "istanbul", "river", "dawn"],
    [
      "istanbul",
      "turkey",
      "bosphorus",
      "伊斯坦布尔",
      "伊斯坦堡",
      "土耳其",
      "博斯普鲁斯",
      "博斯普魯斯",
    ],
    ["all"],
    "warm",
    "50% 40%",
    2,
  ),
  cover(
    "jordan-wadi-desert",
    "destination",
    "Jordanian desert wadi",
    ["middle-east", "jordan", "desert", "wadi", "winter"],
    ["jordan", "wadi", "约旦", "約旦", "沙漠峡谷", "沙漠峽谷"],
    ["winter", "all"],
    "warm",
    "52% 41%",
    2,
  ),
  cover(
    "oman-mountain-wadi",
    "destination",
    "Omani mountain wadi",
    ["middle-east", "oman", "wadi", "mountain", "spring"],
    ["oman", "阿曼", "山谷绿洲", "山谷綠洲"],
    ["spring", "all"],
    "light",
    "50% 42%",
    2,
  ),
  cover(
    "serengeti-dawn",
    "destination",
    "Serengeti at dawn",
    ["africa", "tanzania", "serengeti", "savanna", "wildlife", "dawn"],
    ["serengeti", "tanzania", "塞伦盖蒂", "塞倫蓋蒂", "坦桑尼亚", "坦桑尼亞"],
    ["all"],
    "warm",
    "50% 40%",
    2,
  ),
  cover(
    "zanzibar-stone-town",
    "destination",
    "Zanzibar Stone Town",
    ["africa", "tanzania", "zanzibar", "city", "history"],
    ["zanzibar", "桑给巴尔", "桑給巴爾", "石头城", "石頭城"],
    ["all"],
    "warm",
    "50% 44%",
    2,
  ),
  cover(
    "namibia-dunes",
    "destination",
    "Namibian dunes at dawn",
    ["africa", "namibia", "desert", "dunes", "dawn"],
    ["namibia", "纳米比亚", "納米比亞"],
    ["all"],
    "warm",
    "52% 39%",
    2,
  ),
  cover(
    "cairo-nile-evening",
    "destination",
    "Cairo and the Nile in the evening",
    ["africa", "egypt", "cairo", "river", "night"],
    ["cairo", "egypt", "nile", "开罗", "開羅", "埃及", "尼罗河", "尼羅河"],
    ["all"],
    "dark",
    "50% 41%",
    2,
  ),
  cover(
    "queensland-reef-islands",
    "destination",
    "Queensland reef islands",
    ["oceania", "australia", "queensland", "reef", "island", "summer"],
    ["queensland", "australia", "澳大利亚", "澳大利亞", "昆士兰", "昆士蘭"],
    ["summer", "all"],
    "light",
    "52% 40%",
    2,
  ),

  // 48 activity scenes.
  cover(
    "flight-window",
    "activity",
    "View from an airplane window",
    ["transport", "flight", "sky"],
    [
      "flight",
      "airline",
      "plane",
      "airport",
      "航班",
      "机票",
      "機票",
      "飞机",
      "飛機",
      "机场",
      "機場",
    ],
    ["all"],
    "cool",
    "50% 45%",
  ),
  cover(
    "train-journey",
    "activity",
    "Scenic train journey",
    ["transport", "train", "landscape"],
    ["train", "rail", "铁路", "鐵路", "火车", "火車", "高铁", "高鐵"],
    ["all"],
    "warm",
    "50% 44%",
  ),
  cover(
    "road-trip",
    "activity",
    "Open-road journey",
    ["transport", "car", "road", "landscape"],
    ["road trip", "drive", "rental car", "自驾", "自駕", "租车", "租車", "公路"],
    ["all"],
    "warm",
    "50% 45%",
  ),
  cover(
    "city-walk",
    "activity",
    "Neighbourhood city walk",
    ["city", "walking", "architecture", "slow-travel"],
    ["city walk", "walking", "neighbourhood", "neighborhood", "街区", "街區", "漫步", "步行"],
    ["all"],
    "warm",
    "50% 44%",
  ),
  cover(
    "food-market",
    "activity",
    "Local food market",
    ["food", "market", "culture"],
    [
      "food market",
      "food",
      "restaurant",
      "dining",
      "美食市场",
      "美食市場",
      "菜市场",
      "菜市場",
      "美食",
      "餐厅",
      "餐廳",
      "吃",
    ],
    ["all"],
    "warm",
    "50% 45%",
  ),
  cover(
    "museum-day",
    "activity",
    "Modern museum interior",
    ["culture", "museum", "architecture"],
    [
      "museum",
      "gallery",
      "exhibition",
      "art",
      "博物馆",
      "博物館",
      "美术馆",
      "美術館",
      "展览",
      "展覽",
    ],
    ["all"],
    "light",
    "50% 45%",
  ),
  cover(
    "beach-day",
    "activity",
    "Quiet tropical beach",
    ["beach", "coast", "relax", "summer"],
    ["beach", "island", "seaside", "海滩", "海灘", "海岛", "海島", "海边", "海邊"],
    ["summer", "all"],
    "light",
    "50% 43%",
  ),
  cover(
    "hiking-trail",
    "activity",
    "Mountain hiking trail",
    ["hiking", "mountain", "nature", "outdoor"],
    ["hike", "hiking", "trek", "trail", "徒步", "登山", "远足", "遠足"],
    ["spring", "summer", "autumn"],
    "cool",
    "50% 42%",
  ),
  cover(
    "skiing-morning",
    "activity",
    "Alpine skiing morning",
    ["ski", "snow", "mountain", "winter"],
    ["ski", "skiing", "snowboard", "滑雪", "雪场", "雪場"],
    ["winter"],
    "cool",
    "50% 42%",
  ),
  cover(
    "hot-spring",
    "activity",
    "Open-air hot spring",
    ["wellness", "hot-spring", "nature", "relax"],
    ["hot spring", "onsen", "spa", "温泉", "汤泉", "湯泉"],
    ["autumn", "winter", "spring"],
    "warm",
    "50% 46%",
  ),
  cover(
    "family-trip",
    "activity",
    "Family exploring a waterfront",
    ["family", "walking", "city", "coast"],
    ["family", "kids", "children", "亲子", "親子", "家庭", "孩子", "儿童", "兒童"],
    ["all"],
    "light",
    "50% 43%",
  ),
  cover(
    "romantic-dinner",
    "activity",
    "Intimate terrace dinner",
    ["romantic", "food", "night", "couple"],
    [
      "romantic",
      "honeymoon",
      "anniversary",
      "couple",
      "浪漫",
      "蜜月",
      "纪念日",
      "紀念日",
      "情侣",
      "情侶",
    ],
    ["all"],
    "dark",
    "50% 44%",
  ),
  cover(
    "overnight-train-cabin",
    "activity",
    "Overnight sleeper-train cabin",
    ["transport", "train", "night", "lodging"],
    ["sleeper train", "night train", "train cabin", "卧铺", "臥鋪", "夜车", "夜車"],
    ["all"],
    "dark",
    "52% 45%",
    2,
  ),
  cover(
    "ferry-island-hopping",
    "activity",
    "Ferry island-hopping journey",
    ["transport", "ferry", "island", "coast"],
    ["ferry", "island hopping", "boat trip", "轮渡", "輪渡", "渡轮", "渡輪", "跳岛", "跳島"],
    ["summer", "all"],
    "light",
    "50% 42%",
    2,
  ),
  cover(
    "street-food-tasting",
    "activity",
    "Shared street-food tasting",
    ["food", "street-food", "dining", "market"],
    ["street food", "food tasting", "snacks", "小吃", "街头美食", "街頭美食", "品尝", "品嚐"],
    ["all"],
    "warm",
    "50% 47%",
    2,
  ),
  cover(
    "tea-ceremony-table",
    "activity",
    "Quiet tea tasting",
    ["food", "tea", "culture", "relax"],
    ["tea ceremony", "tea tasting", "tea", "茶道", "品茶", "茶艺", "茶藝"],
    ["all"],
    "warm",
    "50% 47%",
    2,
  ),
  cover(
    "night-market-stroll",
    "activity",
    "Night-market stroll",
    ["culture", "city", "market", "night", "walking"],
    ["night market", "evening market", "夜市美食", "夜市", "夜市场", "夜市場"],
    ["all"],
    "dark",
    "50% 43%",
    2,
  ),
  cover(
    "snorkeling-lagoon",
    "activity",
    "Snorkeling over a lagoon reef",
    ["outdoor", "snorkeling", "ocean", "island", "summer"],
    ["snorkel", "snorkeling", "reef", "浮潜", "浮潛", "珊瑚礁"],
    ["summer", "all"],
    "light",
    "52% 41%",
    2,
  ),
  cover(
    "wellness-retreat-morning",
    "activity",
    "Wellness retreat morning",
    ["wellness", "relax", "lodging", "mountain", "slow-travel"],
    [
      "wellness retreat",
      "meditation retreat",
      "wellness",
      "疗愈",
      "療癒",
      "静修",
      "靜修",
      "养生",
      "養生",
    ],
    ["all"],
    "cool",
    "50% 45%",
    2,
  ),
  cover(
    "ryokan-room-view",
    "activity",
    "Japanese-style guest room and garden",
    ["lodging", "ryokan", "relax", "garden", "autumn"],
    ["ryokan", "japanese inn", "tatami room", "日式旅馆", "日式旅館", "榻榻米"],
    ["autumn", "all"],
    "warm",
    "50% 46%",
    2,
  ),
  cover(
    "multi-generation-family-holiday",
    "activity",
    "Multi-generation family holiday",
    ["family", "group", "walking", "coast", "occasion"],
    [
      "multi generation",
      "multigenerational",
      "family holiday",
      "grandparents",
      "三代同游",
      "三代同遊",
      "全家旅行",
      "祖孙",
      "祖孫",
    ],
    ["spring", "all"],
    "light",
    "50% 43%",
    2,
  ),

  cover(
    "canal-boat-journey",
    "activity",
    "Canal-boat journey",
    ["transport", "boat", "canal", "slow-travel"],
    ["canal boat", "barge trip", "运河船", "運河船", "乘船游", "乘船遊"],
    ["spring", "summer", "all"],
    "cool",
    "52% 44%",
    2,
  ),
  cover(
    "bakery-crawl",
    "activity",
    "Bakery crawl",
    ["food", "bakery", "cafe", "breakfast"],
    ["bakery crawl", "pastry tour", "bakery", "面包店", "麵包店", "烘焙店", "糕点", "糕點"],
    ["all"],
    "light",
    "50% 48%",
    2,
  ),
  cover(
    "vineyard-lunch",
    "activity",
    "Vineyard lunch",
    ["food", "vineyard", "lunch", "countryside", "autumn"],
    ["vineyard lunch", "wine country lunch", "葡萄园午餐", "葡萄園午餐", "酒庄午餐", "酒莊午餐"],
    ["autumn", "all"],
    "warm",
    "50% 47%",
    2,
  ),
  cover(
    "historic-architecture-walk",
    "activity",
    "Historic architecture walk",
    ["culture", "history", "architecture", "walking", "city"],
    [
      "architecture walk",
      "historic walk",
      "建筑漫步",
      "建築漫步",
      "古城步行",
      "历史街区",
      "歷史街區",
    ],
    ["spring", "autumn", "all"],
    "warm",
    "50% 43%",
    2,
  ),
  cover(
    "classical-concert-hall",
    "activity",
    "Classical concert hall",
    ["culture", "music", "concert", "architecture", "night"],
    ["classical concert", "concert hall", "古典音乐会", "古典音樂會", "音乐厅", "音樂廳"],
    ["all"],
    "dark",
    "50% 41%",
    2,
  ),
  cover(
    "alpine-ski-touring",
    "activity",
    "Alpine ski touring",
    ["outdoor", "skiing", "mountain", "winter", "adventure"],
    ["ski touring", "backcountry skiing", "滑雪登山", "野雪", "高山滑雪"],
    ["winter"],
    "light",
    "52% 40%",
    2,
  ),
  cover(
    "coastal-cliff-hike",
    "activity",
    "Coastal cliff hike",
    ["outdoor", "hiking", "coast", "cliffs", "spring"],
    ["coastal hike", "cliff hike", "海岸徒步", "海岸健行", "悬崖徒步", "懸崖健行"],
    ["spring", "summer", "autumn", "all"],
    "cool",
    "50% 42%",
    2,
  ),
  cover(
    "boutique-hotel-breakfast",
    "activity",
    "Boutique hotel breakfast",
    ["lodging", "hotel", "breakfast", "relax"],
    ["hotel breakfast", "boutique hotel", "酒店早餐", "旅店早餐", "精品酒店", "精品旅店"],
    ["all"],
    "warm",
    "50% 48%",
    2,
  ),
  cover(
    "anniversary-city-break",
    "activity",
    "Anniversary city break",
    ["occasion", "couple", "anniversary", "city", "romantic"],
    [
      "anniversary",
      "anniversary trip",
      "city break",
      "周年旅行",
      "纪念日旅行",
      "紀念日旅行",
      "情侣周末",
      "情侶週末",
    ],
    ["autumn", "all"],
    "warm",
    "50% 43%",
    2,
  ),

  cover(
    "campervan-road-trip",
    "activity",
    "Campervan road trip",
    ["transport", "campervan", "road", "nature"],
    ["campervan", "van road trip", "房车旅行", "房車旅行", "露营车", "露營車"],
    ["all"],
    "warm",
    "52% 44%",
    2,
  ),
  cover(
    "taco-cooking-table",
    "activity",
    "Taco cooking table",
    ["food", "cooking", "tacos", "group"],
    ["taco cooking", "tacos", "墨西哥卷饼", "墨西哥捲餅", "塔可", "做饭", "做飯"],
    ["all"],
    "warm",
    "50% 49%",
    2,
  ),
  cover(
    "coffee-farm-tasting",
    "activity",
    "Coffee farm tasting",
    ["food", "coffee", "farm", "tasting", "morning"],
    ["coffee farm", "coffee tasting", "咖啡庄园", "咖啡莊園", "咖啡品鉴", "咖啡品鑑"],
    ["all"],
    "warm",
    "50% 47%",
    2,
  ),
  cover(
    "live-music-evening",
    "activity",
    "Live-music evening",
    ["culture", "music", "night", "city"],
    ["live music", "jazz club", "现场音乐", "現場音樂", "现场演出", "現場演出", "爵士"],
    ["all"],
    "dark",
    "50% 42%",
    2,
  ),
  cover(
    "national-park-camping",
    "activity",
    "National-park camping",
    ["outdoor", "camping", "mountain", "nature", "summer"],
    ["national park camping", "camping", "国家公园露营", "國家公園露營", "露营", "露營"],
    ["summer", "all"],
    "warm",
    "50% 43%",
    2,
  ),
  cover(
    "kayaking-mangroves",
    "activity",
    "Kayaking through mangroves",
    ["outdoor", "kayaking", "mangroves", "water", "adventure"],
    ["mangrove kayaking", "kayaking", "红树林皮划艇", "紅樹林獨木舟", "皮划艇", "獨木舟"],
    ["summer", "all"],
    "light",
    "52% 42%",
    2,
  ),
  cover(
    "beach-resort-hammock",
    "activity",
    "Beach-resort hammock",
    ["lodging", "beach", "hammock", "relax", "summer"],
    ["beach resort", "hammock", "海滩度假", "海灘度假", "吊床", "海岛放松", "海島放鬆"],
    ["summer", "all"],
    "light",
    "50% 45%",
    2,
  ),
  cover(
    "friends-weekend-trip",
    "activity",
    "Friends' weekend trip",
    ["party", "friends", "group", "weekend", "city"],
    [
      "friends trip",
      "weekend with friends",
      "朋友旅行",
      "好友周末",
      "好友週末",
      "结伴旅行",
      "結伴旅行",
    ],
    ["all"],
    "warm",
    "50% 43%",
    2,
  ),
  cover(
    "solo-travel-viewpoint",
    "activity",
    "Solo traveller at a viewpoint",
    ["party", "solo", "viewpoint", "nature", "dawn"],
    ["solo travel", "travel alone", "独自旅行", "獨自旅行", "一个人旅行", "一個人旅行"],
    ["all"],
    "cool",
    "50% 41%",
    2,
  ),

  cover(
    "desert-road-journey",
    "activity",
    "Desert road journey",
    ["transport", "road", "desert", "car"],
    ["desert road trip", "沙漠公路", "荒漠自驾", "荒漠自駕"],
    ["all"],
    "warm",
    "52% 44%",
    2,
  ),
  cover(
    "spice-market-cooking",
    "activity",
    "Spice-market cooking",
    ["food", "cooking", "spices", "market"],
    ["spice cooking", "spice market", "香料烹饪", "香料烹飪", "香料市场", "香料市場"],
    ["all"],
    "warm",
    "50% 49%",
    2,
  ),
  cover(
    "artisan-workshop-visit",
    "activity",
    "Artisan workshop visit",
    ["culture", "artisan", "workshop", "pottery"],
    ["artisan workshop", "craft workshop", "手工艺作坊", "手工藝作坊", "陶艺体验", "陶藝體驗"],
    ["all"],
    "warm",
    "50% 45%",
    2,
  ),
  cover(
    "archaeological-site-walk",
    "activity",
    "Archaeological-site walk",
    ["culture", "history", "archaeology", "walking"],
    ["archaeological site", "ruins walk", "考古遗址", "考古遺址", "古迹步行", "古蹟步行"],
    ["winter", "all"],
    "cool",
    "50% 42%",
    2,
  ),
  cover(
    "safari-game-drive",
    "activity",
    "Safari game drive",
    ["outdoor", "safari", "wildlife", "savanna"],
    ["safari", "game drive", "野生动物游猎", "野生動物遊獵", "观兽", "觀獸"],
    ["all"],
    "warm",
    "52% 42%",
    2,
  ),
  cover(
    "desert-camp-evening",
    "activity",
    "Desert camp in the evening",
    ["lodging", "desert", "camp", "glamping"],
    ["desert camp", "tented camp", "沙漠营地", "沙漠營地", "帐篷营地", "帳篷營地"],
    ["all"],
    "dark",
    "50% 45%",
    2,
  ),
  cover(
    "eco-lodge-rainforest",
    "activity",
    "Rainforest eco-lodge",
    ["lodging", "eco", "rainforest", "relax"],
    ["eco lodge", "rainforest lodge", "生态旅馆", "生態旅館", "雨林旅馆", "雨林旅館"],
    ["all"],
    "cool",
    "50% 44%",
    2,
  ),
  cover(
    "honeymoon-island-escape",
    "activity",
    "Honeymoon island escape",
    ["party", "honeymoon", "couple", "island", "romantic"],
    ["honeymoon island", "honeymoon beach", "海岛蜜月", "海島蜜月", "蜜月旅行"],
    ["all"],
    "warm",
    "50% 43%",
    2,
  ),
  cover(
    "accessible-travel-city-break",
    "activity",
    "Accessible city break",
    ["party", "accessible", "wheelchair", "city"],
    ["accessible travel", "wheelchair travel", "无障碍旅行", "無障礙旅行", "轮椅旅行", "輪椅旅行"],
    ["spring", "all"],
    "light",
    "50% 44%",
    2,
  ),

  // 24 season and weather scenes.
  cover(
    "spring-blossoms",
    "season",
    "Spring blossoms beside a river",
    ["spring", "blossom", "nature"],
    ["spring", "blossom", "cherry", "春天", "春季", "樱花", "櫻花", "花季"],
    ["spring"],
    "light",
    "50% 42%",
  ),
  cover(
    "summer-sunrise",
    "season",
    "Summer coastal sunrise",
    ["summer", "coast", "sunrise"],
    ["summer", "sunrise", "暑假", "夏天", "夏季", "日出"],
    ["summer"],
    "warm",
    "50% 40%",
  ),
  cover(
    "autumn-forest",
    "season",
    "Autumn forest road",
    ["autumn", "forest", "road"],
    ["autumn", "fall foliage", "秋天", "秋季", "红叶", "紅葉", "枫叶", "楓葉"],
    ["autumn"],
    "warm",
    "50% 43%",
  ),
  cover(
    "winter-cabin",
    "season",
    "Winter cabin in fresh snow",
    ["winter", "snow", "cabin", "mountain"],
    ["winter", "snow", "冬天", "冬季", "雪", "木屋"],
    ["winter"],
    "cool",
    "55% 44%",
  ),
  cover(
    "rainy-city",
    "season",
    "Rainy city evening",
    ["rain", "city", "night", "weather"],
    ["rain", "rainy", "monsoon", "下雨", "雨天", "雨季"],
    ["all"],
    "dark",
    "50% 44%",
  ),
  cover(
    "snowy-town",
    "season",
    "Snowy mountain town",
    ["snow", "town", "winter", "night"],
    ["snowy town", "snow village", "雪乡", "雪鄉", "雪镇", "雪鎮"],
    ["winter"],
    "cool",
    "50% 43%",
  ),
  cover(
    "desert-golden-hour",
    "season",
    "Desert at golden hour",
    ["desert", "sunset", "warm", "weather"],
    ["desert", "dunes", "沙漠", "沙丘", "戈壁"],
    ["autumn", "winter", "spring"],
    "warm",
    "50% 42%",
  ),
  cover(
    "northern-lights",
    "season",
    "Northern lights over a lake",
    ["aurora", "night", "winter", "nature"],
    ["aurora", "northern lights", "极光", "極光"],
    ["autumn", "winter", "spring"],
    "dark",
    "50% 38%",
  ),
  cover(
    "spring-rain-garden",
    "season",
    "Spring garden after rain",
    ["spring", "rain", "garden", "flowers"],
    ["spring rain", "rain garden", "春雨", "春季雨天", "雨后花园", "雨後花園"],
    ["spring"],
    "cool",
    "50% 43%",
    2,
  ),
  cover(
    "summer-monsoon-coast",
    "season",
    "Summer monsoon over the coast",
    ["summer", "monsoon", "coast", "storm", "weather"],
    ["monsoon", "summer storm", "rain season", "季风", "季風", "雨季", "夏季暴雨"],
    ["summer"],
    "dark",
    "50% 39%",
    2,
  ),
  cover(
    "autumn-tea-hills",
    "season",
    "Autumn tea hills in mist",
    ["autumn", "tea", "hills", "mist"],
    ["autumn mist", "tea hills", "秋雾", "秋霧", "秋季茶园", "秋季茶園"],
    ["autumn"],
    "warm",
    "52% 41%",
    2,
  ),
  cover(
    "winter-onsen-forest",
    "season",
    "Winter mineral pool in a forest",
    ["winter", "snow", "forest", "hot-spring"],
    ["winter onsen", "snow hot spring", "冬季温泉", "雪中温泉", "雪中溫泉"],
    ["winter"],
    "cool",
    "50% 45%",
    2,
  ),

  cover(
    "spring-meadow-cottage",
    "season",
    "Spring meadow and cottage",
    ["spring", "meadow", "wildflowers", "cottage"],
    ["spring meadow", "wildflowers", "春季草地", "春日草甸", "野花"],
    ["spring"],
    "light",
    "50% 43%",
    2,
  ),
  cover(
    "summer-mediterranean-evening",
    "season",
    "Summer Mediterranean evening",
    ["summer", "coast", "terrace", "evening"],
    ["summer evening", "mediterranean summer", "夏日傍晚", "夏日晚风", "夏日晚風"],
    ["summer"],
    "warm",
    "50% 42%",
    2,
  ),
  cover(
    "autumn-vineyard-mist",
    "season",
    "Autumn vineyard in mist",
    ["autumn", "vineyard", "mist", "countryside"],
    ["autumn vineyard", "vineyard mist", "秋季葡萄园", "秋季葡萄園", "葡萄园晨雾", "葡萄園晨霧"],
    ["autumn"],
    "warm",
    "52% 40%",
    2,
  ),
  cover(
    "winter-european-lake",
    "season",
    "Winter lake at blue hour",
    ["winter", "lake", "snow", "blue-hour"],
    ["winter lake", "frozen lake", "冬季湖泊", "冰封湖面", "冬日蓝调", "冬日藍調"],
    ["winter"],
    "cool",
    "50% 41%",
    2,
  ),

  cover(
    "spring-desert-bloom",
    "season",
    "Spring desert bloom",
    ["spring", "desert", "wildflowers", "nature"],
    ["desert bloom", "spring desert", "沙漠花季", "春季荒漠", "春季荒漠花海"],
    ["spring"],
    "light",
    "50% 43%",
    2,
  ),
  cover(
    "summer-thunderstorm-plains",
    "season",
    "Summer thunderstorm over the plains",
    ["summer", "storm", "grassland", "weather"],
    ["summer thunderstorm", "plains storm", "夏季雷暴", "草原暴雨", "雷雨"],
    ["summer"],
    "dark",
    "50% 37%",
    2,
  ),
  cover(
    "autumn-maple-lake",
    "season",
    "Autumn maple lake",
    ["autumn", "maple", "lake", "reflection"],
    ["autumn maple", "maple lake", "秋日枫林", "秋日楓林", "枫叶湖", "楓葉湖"],
    ["autumn"],
    "warm",
    "50% 41%",
    2,
  ),
  cover(
    "winter-rockies-sunrise",
    "season",
    "Winter Rockies sunrise",
    ["winter", "mountain", "snow", "sunrise"],
    ["winter rockies", "snowy sunrise", "冬季落基山", "雪山日出", "冬日雪山"],
    ["winter"],
    "cool",
    "50% 39%",
    2,
  ),

  cover(
    "spring-wildflower-valley",
    "season",
    "Spring wildflower valley",
    ["spring", "valley", "wildflowers"],
    ["spring wildflower", "wildflower valley", "春季花谷", "春日野花", "野花山谷"],
    ["spring"],
    "light",
    "50% 42%",
    2,
  ),
  cover(
    "summer-tropical-rain",
    "season",
    "Summer tropical rain",
    ["summer", "rain", "tropical", "veranda"],
    ["tropical rain", "summer rain", "热带雨季", "熱帶雨季", "夏日大雨"],
    ["summer"],
    "cool",
    "50% 42%",
    2,
  ),
  cover(
    "autumn-savanna-gold",
    "season",
    "Golden autumn savanna",
    ["autumn", "savanna", "grass", "sunset"],
    ["autumn savanna", "golden grass", "秋季草原", "金色草原", "秋日稀树草原"],
    ["autumn"],
    "warm",
    "50% 41%",
    2,
  ),
  cover(
    "winter-desert-night",
    "season",
    "Winter desert night",
    ["winter", "desert", "night", "stars"],
    ["desert night", "winter stars", "冬季沙漠夜空", "沙漠星空", "冬日星空"],
    ["winter"],
    "dark",
    "50% 39%",
    2,
  ),

  // 24 neutral fallbacks. Unknown titles only draw from this group.
  cover(
    "packed-suitcase",
    "generic",
    "Packed suitcase by a window",
    ["travel", "luggage", "planning"],
    [],
    ["all"],
    "warm",
    "50% 47%",
  ),
  cover(
    "travel-journal",
    "generic",
    "Travel journal and camera",
    ["travel", "planning", "journal"],
    [],
    ["all"],
    "light",
    "50% 48%",
  ),
  cover(
    "airport-terminal",
    "generic",
    "Quiet airport terminal",
    ["travel", "airport", "departure"],
    [],
    ["all"],
    "cool",
    "50% 44%",
  ),
  cover(
    "open-road",
    "generic",
    "Open road toward distant mountains",
    ["travel", "road", "possibility"],
    [],
    ["all"],
    "warm",
    "50% 43%",
  ),
  cover(
    "packing-cubes-flatlay",
    "generic",
    "Packing cubes in a carry-on",
    ["travel", "luggage", "packing", "planning"],
    [],
    ["all"],
    "light",
    "50% 50%",
    2,
  ),
  cover(
    "quiet-departure-lounge",
    "generic",
    "Quiet departure lounge",
    ["travel", "airport", "departure", "waiting"],
    [],
    ["all"],
    "cool",
    "50% 44%",
    2,
  ),
  cover(
    "luggage-carousel-arrival",
    "generic",
    "Luggage carousel on arrival",
    ["travel", "luggage", "airport", "arrival"],
    [],
    ["all"],
    "cool",
    "50% 45%",
    2,
  ),
  cover(
    "route-planning-table",
    "generic",
    "Blank route-planning cards",
    ["travel", "planning", "tools", "itinerary"],
    [],
    ["all"],
    "warm",
    "50% 49%",
    2,
  ),
  cover(
    "train-window-landscape",
    "generic",
    "Countryside through a train window",
    ["travel", "train", "transit", "window"],
    [],
    ["all"],
    "warm",
    "54% 44%",
    2,
  ),
  cover(
    "hotel-key-and-luggage",
    "generic",
    "Hotel key card and luggage",
    ["travel", "hotel", "luggage", "arrival"],
    [],
    ["all"],
    "warm",
    "50% 49%",
    2,
  ),
  cover(
    "rainy-window-departure",
    "generic",
    "Rainy departure window",
    ["travel", "transit", "departure", "rain"],
    [],
    ["all"],
    "cool",
    "52% 43%",
    2,
  ),
  cover(
    "carry-on-cafe-table",
    "generic",
    "Carry-on beside a cafe table",
    ["travel", "luggage", "cafe", "waiting"],
    [],
    ["all"],
    "light",
    "50% 47%",
    2,
  ),
  cover(
    "boarding-gate-silhouette",
    "generic",
    "Travellers at a boarding gate",
    ["travel", "airport", "departure", "waiting"],
    [],
    ["all"],
    "cool",
    "50% 42%",
    2,
  ),
  cover(
    "weekend-bag-entryway",
    "generic",
    "Weekend bag in an entryway",
    ["travel", "luggage", "packing", "weekend"],
    [],
    ["all"],
    "warm",
    "50% 49%",
    2,
  ),
  cover(
    "road-atlas-dashboard",
    "generic",
    "Blank road atlas on a dashboard",
    ["travel", "road", "planning", "map"],
    [],
    ["all"],
    "light",
    "50% 48%",
    2,
  ),
  cover(
    "airport-walkway-light",
    "generic",
    "Empty airport walkway",
    ["travel", "airport", "transit", "walking"],
    [],
    ["all"],
    "cool",
    "50% 43%",
    2,
  ),
  cover(
    "camera-and-sunglasses",
    "generic",
    "Camera and sunglasses",
    ["travel", "camera", "packing", "tools"],
    [],
    ["all"],
    "warm",
    "50% 49%",
    2,
  ),
  cover(
    "reusable-bottle-backpack",
    "generic",
    "Reusable bottle and daypack",
    ["travel", "backpack", "packing", "outdoor"],
    [],
    ["all"],
    "light",
    "50% 49%",
    2,
  ),
  cover(
    "motel-arrival-twilight",
    "generic",
    "Roadside room arrival at twilight",
    ["travel", "lodging", "luggage", "arrival", "road"],
    [],
    ["all"],
    "dark",
    "50% 45%",
    2,
  ),
  cover(
    "itinerary-cards-flatlay",
    "generic",
    "Blank itinerary cards",
    ["travel", "planning", "itinerary", "tools"],
    [],
    ["all"],
    "light",
    "50% 50%",
    2,
  ),
  cover(
    "charging-kit-travel",
    "generic",
    "Travel charging kit",
    ["travel", "charging", "packing", "tools"],
    [],
    ["all"],
    "light",
    "50% 50%",
    2,
  ),
  cover(
    "luggage-rack-room",
    "generic",
    "Suitcase on a luggage rack",
    ["travel", "luggage", "hotel", "arrival"],
    [],
    ["all"],
    "warm",
    "50% 47%",
    2,
  ),
  cover(
    "sunrise-through-window",
    "generic",
    "Sunrise through a travel window",
    ["travel", "window", "transit", "sunrise"],
    [],
    ["all"],
    "warm",
    "52% 42%",
    2,
  ),
  cover(
    "compass-and-boots",
    "generic",
    "Compass and walking boots",
    ["travel", "walking", "outdoor", "tools"],
    [],
    ["all"],
    "warm",
    "50% 49%",
    2,
  ),
] as const;

export interface TravelCoverSubject {
  sessionId: string;
  title?: string | null;
  /** Optional future intent summary or destination hint. */
  hint?: string | null;
}

export interface TravelCoverSelectionOptions {
  /** Covers reserved by another visible surface, such as the Get inspired rail. */
  excludedIds?: ReadonlySet<string>;
}

function normalized(value: string): string {
  return value
    .normalize("NFKC")
    .toLocaleLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .trim();
}

function semanticScore(asset: TravelCoverAsset, text: string): number {
  let score = 0;
  for (const keyword of asset.keywords) {
    const term = normalized(keyword);
    // Latin keywords use token boundaries ("art" must not match "depart"). CJK terms
    // normally have no spaces between words, so substring matching is the useful boundary.
    const matches =
      term.length > 0 &&
      (/[^\x00-\x7F]/.test(term) ? text.includes(term) : ` ${text} `.includes(` ${term} `));
    if (matches) score += 100 + term.length;
  }
  if (score === 0) return 0;
  // An explicit activity is the strongest visual intent ("flights to Shanghai" should
  // look like a flight, not a guessed Shanghai city break). A named destination then
  // outranks seasonal atmosphere ("Kyoto autumn" should still look like Kyoto).
  return score + (asset.kind === "activity" ? 2_000 : asset.kind === "destination" ? 1_000 : 0);
}

/** Stable unsigned hash used only as a deterministic tie-breaker. */
function stableHash(value: string): number {
  let hash = 2166136261;
  for (let i = 0; i < value.length; i++) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

/**
 * Selects one cover per visible Session.
 *
 * Explicit semantic matches win. If no destination/activity/season can be inferred, only
 * generic images are eligible, preventing a greeting or coding Session from being labelled
 * with the wrong city. Covers reserved by another visible rail are removed before matching.
 * Within each candidate set, the Session id provides a stable order and already-used covers
 * move to the back so adjacent cards do not repeat where alternatives exist. When the visible
 * subjects exhaust every semantic match (two "Shanghai" trips, one Shanghai cover), unused
 * generic covers become eligible: a neutral image is honest, a repeat reads as a bug, and a
 * different city's image would be worse than either.
 */
export function selectTravelCovers(
  subjects: readonly TravelCoverSubject[],
  catalog: readonly TravelCoverAsset[] = TRAVEL_COVER_CATALOG,
  options: TravelCoverSelectionOptions = {},
): TravelCoverAsset[] {
  const availableCatalog = catalog.filter((asset) => !options.excludedIds?.has(asset.id));
  const fallback = availableCatalog[0];
  if (!fallback) throw new Error("No travel covers are available");

  const used = new Set<string>();
  return subjects.map((subject) => {
    const text = normalized(`${subject.title ?? ""} ${subject.hint ?? ""}`);
    const scored = availableCatalog
      .map((asset) => ({ asset, score: semanticScore(asset, text) }))
      .filter(({ score }) => score > 0);
    const generics = availableCatalog
      .filter((asset) => asset.kind === "generic")
      .map((asset) => ({ asset, score: 0 }));
    const matched = scored.length ? scored : generics;
    const candidates = matched.every(({ asset }) => used.has(asset.id))
      ? [...matched, ...generics.filter(({ asset }) => !used.has(asset.id))]
      : matched;
    const ranked = [...candidates].sort(
      (a, b) =>
        Number(used.has(a.asset.id)) - Number(used.has(b.asset.id)) ||
        b.score - a.score ||
        stableHash(`${subject.sessionId}:${a.asset.id}`) -
          stableHash(`${subject.sessionId}:${b.asset.id}`),
    );
    const selected = ranked[0]?.asset ?? fallback;
    used.add(selected.id);
    return selected;
  });
}
